# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e37fec272a14d83c7541078ed7827f0c9426b2661d7f7f410ad2b47a851868ca494d41814944be0498ca9aaf8dcd666d4953c74b10794fed5abbbae7a8d4328

test:
  secret_key_base: 466eb51d6884801986837f06f67f9859f98c1b4568d4d2e993a2a3f0a77c3863ba3c5150249cbe0b42d43e0daadc69e8e3d6ec3443c6f2ae029aeb5834a25d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
